import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Layout from "../components/Layout";
import { Section, SectionTitle, SectionText } from "../styles/GlobalComponents";

const ArtContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  width: 100rem;
  margin: 8rem 0;
`;

const ImageContainer = styled.div`
  margin: 0.5rem;
  width: 40rem;
  height: 40rem;
  position: relative;
`;

export default function GraphicDesign() {
  return (
    <>
      <Head>
        <title>GRAPHIC DESIGN | ANDREA WILSON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Section>
          <SectionTitle>TYPE AS EDITORIAL</SectionTitle>
          <SectionText>
            Editorial design projects which involved exploring different
            typefaces, their histories and classifications through reading and
            research. Each student chose two different typefaces to examine and
            create an editorial style spread. The purpose of the assignment was
            to gain experience using type and elements of design to enhance
            meaning and to develop an appreciation of type as letter forms in
            composition.
          </SectionText>
        </Section>
      </Layout>
    </>
  );
}
