import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Layout from "../components/Layout";
import { Section, SectionTitle, SectionText } from "../styles/GlobalComponents";
import { editorialProjects } from "../constants";

const ArtContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  width: 100rem;
  margin-top: 3rem;
`;

const ImageContainer = styled.div`
  margin: 0.5rem;
  width: 90rem;
  height: 40rem;
  position: relative;
`;

export default function GraphicDesign() {
  return (
    <>
      <Head>
        <title>GRAPHIC DESIGN | ANDREA WILSON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Section>
          <SectionTitle>TYPE AS EDITORIAL</SectionTitle>
          <SectionText>
            Editorial design projects which involved exploring different
            typefaces, their histories and classifications through reading and
            research. Each student chose two different typefaces to examine and
            create an editorial style spread. The purpose of the assignment was
            to gain experience using type and elements of design to enhance
            meaning and to develop an appreciation of type as letter forms in
            composition.
          </SectionText>
          <ArtContainer>
            {editorialProjects.map(({ title, description, image, id }) => {
              return (
                <ImageContainer key={id}>
                  <Image src={image} alt={title} width={4500} height={2038} />
                </ImageContainer>
              );
            })}
          </ArtContainer>
        </Section>
        <Section>
          <SectionTitle>SUPERKIDS</SectionTitle>
          <SectionText>
            This was a vitamin packaging project in which we had to research two
            different vitamin types, choose a theme, and design wrap around
            bottle labels for them. Using a bright and friendly color palette,
            and fun cartoon characters on the bottles, I wanted my target
            audience to respond with enthusiasm and an eagerness to give this
            product to their kids with trust, and to hopefully make it a little
            easier for their kids to take their vitamins.
          </SectionText>
          <ArtContainer>
            {editorialProjects.map(({ title, description, image, id }) => {
              return (
                <ImageContainer key={id}>
                  <Image src={image} alt={title} width={4500} height={2038} />
                </ImageContainer>
              );
            })}
          </ArtContainer>
        </Section>
      </Layout>
    </>
  );
}
