import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const HomeContainer = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 1274px;
`;

const HomeContent = styled.div`
  display: flex;
  flex-direction: column;
  margin-top: 12rem;
  /* margin-right: 7rem; */
  justify-content: center;
  align-items: flex-end;
  position: relative;
  height: 1073px;
  border: 1px solid red;
  width: 100vw;
`;

const PinkRectangle = styled.div`
  height: 1073px;
  width: 1181px;
  background-color: ${({ theme }) => theme.colors.pink};
  position: absolute;
  right: 630px;
  z-index: -1;

  @media screen and (max-width: 1462px) {
    right: 545px;
  }

  @media ${({ theme }) => theme.breakpoints.xl} {
    right: 430px;
  }
`;

const HeroText = styled.h1`
  font-size: 9.6rem;
  font-family: ${({ theme }) => theme.fonts.luloBold};
  color: ${({ theme }) => theme.colors.pink};
  text-align: right;
  line-height: 1.5;

  @media screen and (max-width: 1462px) {
    font-size: 8.3rem;
  }

  @media ${({ theme }) => theme.breakpoints.xl} {
    font-size: 6.8rem;
    letter-spacing: 0;
  }
`;

const WhiteText = styled.span`
  color: white;
`;

const HeaderTop = styled.div`
  margin-top: 12rem;
  margin-bottom: -7.5rem;
  max-width: 1462px;
  width: 100vw;
`;

const HeaderBottom = styled.div`
  display: flex;
  justify-content: space-between;
  width: 1200px;
  margin-right: 2.8rem;
  /* border: 1px solid orange; */

  @media screen and (max-width: 1462px) {
    width: 1045px;
    margin-right: 2.2rem;
    margin-top: 1rem;
  }
`;

const SubHeader = styled.h2`
  font-family: ${({ theme }) => theme.fonts.futuraBook};
  font-size: 1.8rem;
  letter-spacing: 0.1rem;
  color: white;
`;

const LinkContainer = styled.nav`
  display: flex;
  flex-direction: column;
  margin-top: 1rem;
`;

const NavLink = styled.a`
  color: ${({ theme }) => theme.colors.gray};
  text-align: right;
  font-family: ${({ theme }) => theme.fonts.luloBold};
  font-size: 1.2rem;
  letter-spacing: 0.1rem;
  margin-bottom: 1.8rem;

  :hover {
    color: ${({ theme }) => theme.colors.pink};
  }
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>HOME | ANDREA WILSON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContainer>
        <HomeContent>
          <PinkRectangle />
          <HeaderTop>
            <HeroText>
              <WhiteText>HELLO, MY</WhiteText> NAME IS
              <br />
              <WhiteText>ANDREA</WhiteText> WILSON
            </HeroText>
          </HeaderTop>
          <HeaderBottom>
            <SubHeader>PRODUCTION ARTIST / GRAPHIC DESIGNER</SubHeader>
            <LinkContainer>
              <Link href="/" passHref>
                <NavLink>HOME</NavLink>
              </Link>
              <Link href="/production-art" passHref>
                <NavLink>PRODUCTION ART</NavLink>
              </Link>
              <Link href="/tatcha" passHref>
                <NavLink>TATCHA</NavLink>
              </Link>
              <Link href="/graphic-design" passHref>
                <NavLink>GRAPHIC DESIGN</NavLink>
              </Link>
              <Link href="/fine-art" passHref>
                <NavLink>FINE ART</NavLink>
              </Link>
              <Link href="/images/andrea-wilson-resume.pdf" passHref>
                <NavLink target="_blank" rel="noreferrer noopener">
                  RESUME
                </NavLink>
              </Link>
            </LinkContainer>
          </HeaderBottom>
        </HomeContent>
      </HomeContainer>
    </div>
  );
}
