import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Layout from "../components/Layout";
import {
  Section,
  SectionTitle,
  SectionText,
  CopyrightText,
} from "../styles/GlobalComponents";
import { tatchaArt } from "../constants";

const ArtContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  width: 100rem;
  margin: 8rem 0;
`;

const ImageContainer = styled.div`
  margin: 0.5rem;
  width: 40rem;
  height: 40rem;
  position: relative;
`;

export default function Tatcha() {
  return (
    <>
      <Head>
        <title>TATCHA | ANDREA WILSON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Section>
          <SectionTitle>TATCHA</SectionTitle>
          <SectionText>
            In my current role at Tatcha as a Packaging Production Designer, I
            focus mainly on artwork layout and typography, laying out artwork on
            a variety of skin care and beauty packaging. Here is just a sample
            of products I&apos;ve helped to produce.
          </SectionText>
          <CopyrightText>All artwork © TATCHA, 2021</CopyrightText>
          <ArtContainer>
            {tatchaArt.map(({ image, id }) => (
              <ImageContainer key={id}>
                <Image
                  src={image}
                  alt="Tatcha Products"
                  layout="fill"
                  objectFit="cover"
                  objectPosition="50% 77%"
                  width={1440}
                  height={1800}
                />
              </ImageContainer>
            ))}
          </ArtContainer>
        </Section>
      </Layout>
    </>
  );
}
